### ISSUE TITLE
Ah oh, hope this helps.

### ISSUE THREAD

**Issue by celittle3** [EwyBoy/Hammer-Time#6]
I was mining normal stone and got this crash.

ava.lang.NullPointerException: Unexpected error
	at com.ewyboy.hammertime.items.ItemBaseTool.func_179218_a(ItemBaseTool.java:55)
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:376)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187103_a(PlayerControllerMP.java:166)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:248)
	at PlayerControllerOF.func_180511_b(PlayerControllerOF.java:49)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:334)
	at PlayerControllerOF.func_180512_c(PlayerControllerOF.java:65)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1478)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.ewyboy.hammertime.items.ItemBaseTool.func_179218_a(ItemBaseTool.java:55)
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:376)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187103_a(PlayerControllerMP.java:166)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:248)
	at PlayerControllerOF.func_180511_b(PlayerControllerOF.java:49)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:334)
	at PlayerControllerOF.func_180512_c(PlayerControllerOF.java:65)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1478)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

**Comment by EwyBoy** [comment]
Thanks, gonna look into it.

**Comment by EwyBoy** [comment]
Fixed in version 2.2.0
